<link rel="stylesheet" type="text/css" href="../css/reset.min.css">
<link rel="stylesheet" type="text/css" href="../css/theme_common.css">
<link rel="stylesheet" type="text/css" href="../css/ucenter.css">
<link rel="stylesheet" type="text/css" href="../css/log.css">
<link rel="stylesheet" type="text/css" href="../common/layui/css/layui.css">

<script src="../js/jquery.min.js" type="text/javascript" charset="utf-8"></script>
<script src="../js/ucenterPublic.js" type="text/javascript" charset="utf-8"></script>
<script src="../js/json.parse.js" type="text/javascript" charset="utf-8"></script>
<script src="../js/jquery.form.js" type="text/javascript" charset="utf-8"></script>
<script src="../common/validate.js" type="text/javascript" charset="utf-8"></script>
<script src="../common/commonUtil.js" type="text/javascript" charset="utf-8"></script>
<script src="../common/menucookie.js" type="text/javascript" charset="utf-8"></script>
<script src="../common/layer/layer.js" type="text/javascript" charset="utf-8"></script>
<script src="../common/layui/layui.js" type="text/javascript" charset="utf-8"></script>

<script type="text/javascript" src="../common/calendar/WdatePicker.js"></script>
<script type="text/javascript" src="../common/xwin.js"></script>
<script type="text/javascript" src="../common/main.js"></script>
<script type="text/javascript" src="../common/searchUtils.js"></script>
<script type="text/javascript" src="../common/queryUtils.js"></script>
<script type="text/javascript" src="../common/tableManager.js"></script>
<script type="text/javascript" src="../common/list.js"></script>
<script type="text/javascript" src="../common/common.js"></script>

<!--[if lt IE 9]>
<script src="../js/html5shiv.min.js" type="text/javascript" charset="utf-8"></script>
<script src="../js/respond.min.js" type="text/javascript" charset="utf-8"></script>
<![endif]-->
<style type="text/css" ></style><script>//console.log('a')
</script><style type="text/css">object,embed{                -webkit-animation-duration:.001s;-webkit-animation-name:playerInserted;                -ms-animation-duration:.001s;-ms-animation-name:playerInserted;                -o-animation-duration:.001s;-o-animation-name:playerInserted;                animation-duration:.001s;animation-name:playerInserted;}                @-webkit-keyframes playerInserted{from{opacity:0.99;}to{opacity:1;}}                @-ms-keyframes playerInserted{from{opacity:0.99;}to{opacity:1;}}                @-o-keyframes playerInserted{from{opacity:0.99;}to{opacity:1;}}                @keyframes playerInserted{from{opacity:0.99;}to{opacity:1;}}</style></head>